# Introduction

Commercial insurance programs are often depicted as "towers." (See Figure \ref{fig:tower}) The lowest floors of the tower are typically comprised of risk retained by the insured. The middle floors include commercially insured working layers.  High-layer excess insurance occupy the penthouse. 

Each of these layers has a cost to it.

-   The cost of the lowest layers will have a reasonable degree of predictability. The cost for these layers will be principally be the expected loss with a minimal capital charge for volatility. There may also be frictional costs associated with risk retention such as increased audit and actuarial fees and claims costs from legal counsel and third party claim administrators.
-   The middle layers provide coverage for claims related to events that occur with a degree of regularity. The amount of claims may not be reasonably predictable in a single year but it would be predictable over a longer-term time horizon. They insurance coverage provides value to the insured by smoothing claim volatility over time. There may be multiple insurers in the higher working layers.
-   Insureds generally do not expect access coverage from the highest layers. The expected claims will likely be close to \$0. For the insured-insurer relationship, this layer provides some smoothing of claims volatility over time. However, insurance in this layer smooth claim volatility across risks. As a result, there are often multiple insurers in these layers, each with a pro-rata share. 

```{r insurance tower, echo=FALSE, fig.height=4, fig.width=3, fig.cap= "\\label{fig:tower}Example Insurance Tower"}
par(mar = c(1, 0, 0, 0))
plot(x = rep(x = 1, times = 10), y = 1:10, type = 'n', xlim = c(0.8, 1.2),
  bty = 'n', axes = FALSE, ylim = c(0, 14), ylab = '', xlab = '')
rect(xleft = 0.9, ybottom = 0.01, xright = 1.1, ytop = 2)
rect(xleft = 0.9, ybottom = 2, xright = 1.1, ytop = 5)
rect(xleft = 0.9, ybottom = 5, xright = 1.1, ytop = 8)
rect(xleft = 0.9, ybottom = 8, xright = 1.1, ytop = 13, col = 'grey90')
text(x = 1, y = 1, label = '$1 million retention', cex = 0.7)
text(x = 1, y = 3.75, label = 'First Layer Excess\n$9 million\nInsurer A', cex = 0.7)
text(x = 1, y = 6.75, label = 'Second Layer Excess\n$20 million\nInsurer B (60%)\nInsurer C (40%)', cex = 0.7)
text(x = 1, y = 11, label = 'Third Layer Excess\n$50 million\nInsurer D (50%)\nInsurer E (30%)\nInsurer F (20%)', cex = 0.7)
text(x = 0.85, y = 7, srt = 90, label = 'Coverage Layer\n(not to scale)', cex = 0.7)
```

