## A Pedagogical Example

To support the reader's understanding of the concepts presented in this paper, we offer the following pedagogical example. We offer the hypothetical airline "PC Air."

-   PC Air leases a single plane.

-   PC Air's offers cargo transport between New York and Los Angeles. That route requires PC Air's plane to fly over several major ground structures (such as warehouses). PC Air only flies overnight when these structures are not occupied.

-   PC Air developed a technology that allows it to fly its plan remotely (no pilot).

-   Airplane crashes are exceeding rare.

-   PC Air's enterprise risk management targets solvency if its plan were to crash in a remote area. That is, it would be able to reimburse its cargo customers and pay for the owner of the cost of the plane. Its remaining capital would be sufficient for it to lease a new plane. If PC Air's plane were to cause damage to ground structures, it would declare bankruptcy.

Throughout this paper, we will refer back to the example of PC Air to help the reader understand that how these concepts work in practice.
