## The No Insurance Base Case

We start by considering the no insurance base case. For simplicity, we assume that only one claim can occur during the policy period.

Under these conditions:

-   $C_w = C_0 - S$ The firm's (beginning) working capital is equal to its total capital less the amount that it elects to set aside for potential claims event.

-   The change in capital ($\Delta C$) depends upon whether a loss event occurs.

    -   No loss event ($n$ = 0): $\Delta C = R - Z$

    -   Loss event occurs ($n$ = 1): $\Delta C = R - Z - X$. Critically, we recognize that a portion of the distribution of $\Delta C$ is greater than $C - C_m$. For these realziations of \$X\$, the firm must declare bankruptcy.

## The Insurance Case

If the firm elects to purchase insurance, then:

-   $C_w = C_I - P$ The insured will need to pay premium but it no longer needs to set aside capital to cover potential claim events.

-   The change in capital is no longer depends on whether a loss occurs: $\Delta C = R - Z - P$.

