## Capital Implications of Loss Outcomes
We can now consider the capital implications of loss outcomes. We start with the no insurance base case.

## The No-Insurance Base Case
We consider three different potential outcomes:

* In the no loss scenario, the firm does not experience an loss event.
* In Loss Scenario 1, the firm experiences a loss that has a value which is less than it's reserves.
* In Loss Scenario 2, the firm experiences a loss that depletes capital to level which remains above the working capital.
* In Loss Scenario 3, the firm experiences a loss event but which is greater than the difference between its starting capital and its minimum capital.

```{r}
par(mar = c(1, 1, 1, 1))

center <- 1
plot(x = 1, y = 1, type = 'n', xlim = c(0.9, 2),
  bty = 'n', axes = FALSE, ylim = c(0, 8), ylab = '', xlab = '')
rect(xleft = center - 0.1, ybottom = 0, xright = center + 0.1, ytop = 5)
rect(xleft = center - 0.1, ybottom = 5, xright = center + 0.1, ytop = 7, 
  col = 'grey90')
text(x = center, y = 3, label = 'Working Capital', cex = 0.7)
text(x = center, y = 6.0, label = 'Reserves\n(Segregated Capital)', cex = 0.7)
text(x = center, y = 7.4, label = 'Starting Capital', cex = 0.7)
text(x = center, y = 1.75, label = 'Minimum Working Capital', col = 'red' , pos = 3, cex = 0.7)
abline(h = 1.75, col = 'red')

center <- center + 0.3
rect(xleft = center - 0.1, ybottom = 0, xright = center + 0.1, ytop = 5)
rect(xleft = center - 0.1, ybottom = 0, xright = center + 0.1, ytop = 7)
text(x = center, y = 3, label = 'Working Capital', cex = 0.7)
text(x = center, y = 6.0, label = 'Excess Capital', cex = 0.7)
text(x = center, y = 7.4, label = 'Ending Capital\nNo Loss Secnario', cex = 0.7)

center <- center + 0.3
rect(xleft = center - 0.1, ybottom = 0, xright = center + 0.1, ytop = 6)
rect(xleft = center - 0.1, ybottom = 6, xright = center + 0.1, ytop = 7, 
  lty = 'dashed')
text(x = center, y = 3, label = 'Working Capital', cex = 0.7)
text(x = center, y = 6.5, label = 'Required\nReplenishment', cex = 0.7)
text(x = center, y = 7.4, label = 'Ending Capital\nLoss Scenario 1', cex = 0.7)

center <- center + 0.3
rect(xleft = center - 0.1, ybottom = 0, xright = center + 0.1, ytop = 3)
rect(xleft = center - 0.1, ybottom = 3, xright = center + 0.1, ytop = 7,
  lty = 'dashed')
text(x = center, y = 2, label = 'Working Capital', cex = 0.7)
text(x = center, y = 6.5, label = 'Required\nReplenishment', cex = 0.7)
text(x = center, y = 7.4, label = 'Ending Capital\nLoss Scenario 2', cex = 0.7)

center <- center + 0.3
rect(xleft = center - 0.1, ybottom = 0, xright = center + 0.1, ytop = 1.5)
text(x = center, y = 1, label = 'Working Capital', cex = 0.7)
text(x = center, y = 6.5, label = 'Bankruptcy', cex = 0.7)
text(x = center, y = 7.4, label = 'Ending Capital\nLoss Scenario 2', cex = 0.7)


```








I use notation $F_1$ to represent a penalty factor(\>=1). This factor comes from the indirect loss when loss is over the reserve

I use notation $F_2$ to represent a penalty factor(\>=1). This factor comes from the illiquidity when loss reach the fixed assets

The detail is in the following formula an I think it answers the question how does the cost of capital increase as you get closer to minimum capital\

$$
X_c=\left\{
             \begin{array}{lr}
             0 & X=0\\
             X & 0< X\leq Res\\
             Res+F_1\ (X-Res) , & Res< X\leq Res+C_w\\
             Res+F_1\ (X-Res)+F_2\ (X-Res-C_w) , & Res< X\leq S\\
             Bankrupt &X>S  
             \end{array}
\right.
$$

The Capital would get both a F1 and F2 penalty when its loss is over (reserve + working capital), F1 and F2 are independent. Here an assumption is used to simplify the problem (the company would start to loss it fixed assets after losing all its working capital, which is not inconsistent with reality)

First, in the notation, we use R to represent the Revenue for the product or service sold by the insured. I suggest using R to represent a return rate otherwise a quantity, since under the no insurance & with insurance cases, $C_w$ would be different, holding more working capital to operate would be a motivation to choose that strategy, using a return rate can better quantify.

Then, I think the Capital Loss for companies will not be exactly the amount of loss, but also depend on the reserve and $C_w$ amount.

I use notation $X_c$ to represent the Capital Loss

After refining some concepts, $C_w=C-Res-Fixed\ Assets$

We can use ROC(Return of capital) as a measurement for the return performance

1 No loss

$\Delta C=R-Z$, $ROC=\frac{R-Z}{C}$

2 A loss that allows the firm to continue operations,what happens if you drop below the minimum capital in terms of the cost to recapitalize

$\Delta C=R-Z-X_c$, $ROC=\frac{R-Z-X_c}{C}$

If the excess loss happens, company's debt would increase rapidly. There are the following 3 methods can help company overcome the high debt.

1)  Debt Restructuring\
    The debt restructuring process typically involves reducing the interest rates on loans, extending the dates when the company's liabilities are due to be paid, or both. These steps improve the firm's chances of paying back the obligations. Creditors understand that they would receive even less should the company be forced into bankruptcy or liquidation. Debt restructuring can be a win-win for both entities because the business avoids bankruptcy, and the lenders typically receive more than what they would through a bankruptcy proceeding.

2)  Reorganization\
    Federal bankruptcy laws govern how companies go out of business or recover from crippling debt.\
    Ch11/13 Reorganization\
    Ch7 Liquidate\
    The reorganization is not the real bankrupt. It allows companies to pay off their creditors and emerge from bankruptcy in a stronger position. It is more like a buffer before the liquidates to keep the company continue its day-to-day operation and try to become profitable again.

3)  If the company's debt situation is not so severe. There are several ways for companies to raise money.\
    1.If the company is a public company, it can issue stocks or bonds.\
    2.If the company is a nonpublic company, borrowing money from banks would be a more common way.\
    One thing to note, after a high layer loss, the company's operation could be affected and have a more chance to bankrupt, its stock price would decrease, its bond rating may decrease (which means it needs to pay higher interest for the bonds issued), the bank may reject or charge a higher interest rate when lending money to you.
