# Complete Algebreic Derivation of Value Creation Equations

## Capital Deployment Value Creation Equation
\begin{align}
\nonumber E[R^I] &> E[R^0] \\
\nonumber r_c \times (C - P^{I}) - P^{I} &> r_c \times C_{w}^{I} + r_f \times C_{x}^{0} \\
\nonumber r_c \times C - r_c \times P^{I} - P^{I} &>  r_c \times C_{w}^{I} + r_f \times C_{x}^{0}\\
\nonumber -P^{I} \times (1 + r_c) &> r_c \times C_{w}^{I} + r_f \times C_{x}^{0} - r_c \times C\\
\nonumber -P^{I} \times (1 + r_c) &> r_c \times (C_{w}^{I} - C) + r_f \times C_{x}^{0}\\
\nonumber -P^{I}  &> \dfrac{r_c \times (C_{w}^{I} - C) + r_f \times C_{x}^{0}}{1 + r_c}\\
\nonumber -P^{I} &> \dfrac{r_c \times (C_{w}^{I} - C) + r_f \times C_{x}^{0}}{1 + r_c}\\
\nonumber -P^{I} &> \dfrac{r_c \times (-C_{x}^{0}) + r_f \times C_{x}^{0}}{1 + r_c}\\
\nonumber -P^{I} &> C_{x}^{0} \times \dfrac{r_f - r_c}{1 + r_c}\\
P^{I} &< C_{x}^{0} \times \dfrac{r_c - r_f}{1 + r_c} \label{eqn:cap-deploy}
\end{align}

## Complete Value Creation Equation

\begin{align}
\nonumber \text{Sharpe Ratio}^I &> \text{Sharpe Ratio}^0\\
\nonumber \dfrac{C\times (r_c-r_f)-P^{I} \times(1 + r_c)}{SD(X_{ret})} &> \dfrac{(C-C_{x}^{0})\times (r_c-r_f)}{SD(X)}\\
\nonumber C\times (r_c-r_f)-P^{I} \times(1 + r_c) &> \dfrac{SD(X_{ret})}{SD(X)} \times (C-C_{x}^{0})\times (r_c-r_f)\\
\nonumber -P^{I} \times(1 + r_c) &> \dfrac{SD(X_{ret})}{SD(X)}\times (C-C_{x}^{0}) \times (r_c-r_f)\\
\nonumber &\mathrel{\phantom{<}} \quad - C \times (r_c-r_f)\\
\nonumber -P^{I} \times(1 + r_c) &> (r_c-r_f) \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (C-C_{x}^{0}) - C\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (C_{x}^{0}- C) + C\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times C_{x}^{0}\right.\\
\nonumber &\mathrel{\phantom{<}}\left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times C_{x}^{0}\right.\\
\nonumber &\mathrel{\phantom{<}} \left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C_{x}^{0} + C_{w}^{0}\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{x}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times C_{x}^{0}\right.\\
\nonumber &\mathrel{\phantom{<}}\left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C_{w}^{0}\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{x}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (C - C_{w}^{0})\right.\\
\nonumber &\mathrel{\phantom{<}}\left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C_{w}^{0}\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{x}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (-C_{w}^{0})  + C_{w}^{0}\right]\\
P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{x}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{w}^{0} \times \left[1 - \dfrac{SD(X_{ret})}{SD(X)}\right] \label{final}
\end{align}
