---
title: "Untitled"
author: "Zhenkai Zhu and Rajesh Sahasrabbuddhe"
date: "2/20/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Value Creation
The insurance purchase created value when it results in an increase in the Sharpe Ratio. 

\begin{align}
\begin{aligned}
\nonumber \text{Sharpe Ratio}^I &> \text{Sharpe Ratio}^0\\
\nonumber \dfrac{C\times (r_c-r_f)-P^{I} \times(1 + r_c)}{SD(X_{ret})} &> \dfrac{(C-C_{X}^{0})\times (r_c-r_f)}{SD(X)}\\ 
\nonumber C\times (r_c-r_f)-P^{I} \times(1 + r_c) &> \dfrac{SD(X_{ret})}{SD(X)} \times (C-C_{X}^{0})\times (r_c-r_f)\\ 
\nonumber -P^{I} \times(1 + r_c) &> \dfrac{SD(X_{ret})}{SD(X)}\times (C-C_{X}^{0}) \times (r_c-r_f)\\
\nonumber &\mathrel{\phantom{<}} \quad - C \times (r_c-r_f)\\
\nonumber -P^{I} \times(1 + r_c) &> (r_c-r_f) \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (C-C_{X}^{0}) - C\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (C_{X}^{0}- C) + C\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times C_{X}^{0}\right.\\ 
\nonumber &\mathrel{\phantom{<}}\left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times C_{X}^{0}\right.\\
\nonumber &\mathrel{\phantom{<}} \left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C_{X}^{0} + C_{W}^{0}\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{X}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times C_{X}^{0}\right.\\
\nonumber &\mathrel{\phantom{<}}\left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C_{W}^{0}\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{X}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (C - C_{W}^{0})\right.\\
\nonumber &\mathrel{\phantom{<}}\left. \quad - \dfrac{SD(X_{ret})}{SD(X)}\times C + C_{W}^{0}\right]\\
\nonumber P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{X}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times \left[\dfrac{SD(X_{ret})}{SD(X)}\times (-C_{W}^{0})  + C_{W}^{0}\right]\\ 
P^{I} &< \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{X}^{0} + \dfrac{(r_c-r_f)}{(1 + r_c)} \times C_{W}^{0} \times \left[1 - \dfrac{SD(X_{ret})}{SD(X)}\right] \label{final}
\end{aligned}
\end{align}
